/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginRoleRouteImport } from './routes/login.$role'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedModulesUiuxRouteImport } from './routes/_authenticated/modules/uiux'
import { Route as AuthenticatedModulesTestsRouteImport } from './routes/_authenticated/modules/tests'
import { Route as AuthenticatedModulesTeamRouteImport } from './routes/_authenticated/modules/team'
import { Route as AuthenticatedModulesSecurityRouteImport } from './routes/_authenticated/modules/security'
import { Route as AuthenticatedModulesRisksRouteImport } from './routes/_authenticated/modules/risks'
import { Route as AuthenticatedModulesRequirementsRouteImport } from './routes/_authenticated/modules/requirements'
import { Route as AuthenticatedModulesRepositoryRouteImport } from './routes/_authenticated/modules/repository'
import { Route as AuthenticatedModulesQualityRouteImport } from './routes/_authenticated/modules/quality'
import { Route as AuthenticatedModulesKnowledgeRouteImport } from './routes/_authenticated/modules/knowledge'
import { Route as AuthenticatedModulesDocumentationRouteImport } from './routes/_authenticated/modules/documentation'
import { Route as AuthenticatedModulesDatabaseRouteImport } from './routes/_authenticated/modules/database'
import { Route as AuthenticatedModulesAssistantRouteImport } from './routes/_authenticated/modules/assistant'
import { Route as AuthenticatedModulesArchitectureRouteImport } from './routes/_authenticated/modules/architecture'
import { Route as AuthenticatedModulesApiRouteImport } from './routes/_authenticated/modules/api'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoleRoute = LoginRoleRouteImport.update({
  id: '/login/$role',
  path: '/login/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesUiuxRoute =
  AuthenticatedModulesUiuxRouteImport.update({
    id: '/modules/uiux',
    path: '/modules/uiux',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesTestsRoute =
  AuthenticatedModulesTestsRouteImport.update({
    id: '/modules/tests',
    path: '/modules/tests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesTeamRoute =
  AuthenticatedModulesTeamRouteImport.update({
    id: '/modules/team',
    path: '/modules/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesSecurityRoute =
  AuthenticatedModulesSecurityRouteImport.update({
    id: '/modules/security',
    path: '/modules/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesRisksRoute =
  AuthenticatedModulesRisksRouteImport.update({
    id: '/modules/risks',
    path: '/modules/risks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesRequirementsRoute =
  AuthenticatedModulesRequirementsRouteImport.update({
    id: '/modules/requirements',
    path: '/modules/requirements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesRepositoryRoute =
  AuthenticatedModulesRepositoryRouteImport.update({
    id: '/modules/repository',
    path: '/modules/repository',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesQualityRoute =
  AuthenticatedModulesQualityRouteImport.update({
    id: '/modules/quality',
    path: '/modules/quality',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesKnowledgeRoute =
  AuthenticatedModulesKnowledgeRouteImport.update({
    id: '/modules/knowledge',
    path: '/modules/knowledge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesDocumentationRoute =
  AuthenticatedModulesDocumentationRouteImport.update({
    id: '/modules/documentation',
    path: '/modules/documentation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesDatabaseRoute =
  AuthenticatedModulesDatabaseRouteImport.update({
    id: '/modules/database',
    path: '/modules/database',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesAssistantRoute =
  AuthenticatedModulesAssistantRouteImport.update({
    id: '/modules/assistant',
    path: '/modules/assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesArchitectureRoute =
  AuthenticatedModulesArchitectureRouteImport.update({
    id: '/modules/architecture',
    path: '/modules/architecture',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesApiRoute = AuthenticatedModulesApiRouteImport.update({
  id: '/modules/api',
  path: '/modules/api',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/login/$role': typeof LoginRoleRoute
  '/login/': typeof LoginIndexRoute
  '/modules/api': typeof AuthenticatedModulesApiRoute
  '/modules/architecture': typeof AuthenticatedModulesArchitectureRoute
  '/modules/assistant': typeof AuthenticatedModulesAssistantRoute
  '/modules/database': typeof AuthenticatedModulesDatabaseRoute
  '/modules/documentation': typeof AuthenticatedModulesDocumentationRoute
  '/modules/knowledge': typeof AuthenticatedModulesKnowledgeRoute
  '/modules/quality': typeof AuthenticatedModulesQualityRoute
  '/modules/repository': typeof AuthenticatedModulesRepositoryRoute
  '/modules/requirements': typeof AuthenticatedModulesRequirementsRoute
  '/modules/risks': typeof AuthenticatedModulesRisksRoute
  '/modules/security': typeof AuthenticatedModulesSecurityRoute
  '/modules/team': typeof AuthenticatedModulesTeamRoute
  '/modules/tests': typeof AuthenticatedModulesTestsRoute
  '/modules/uiux': typeof AuthenticatedModulesUiuxRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/login/$role': typeof LoginRoleRoute
  '/login': typeof LoginIndexRoute
  '/modules/api': typeof AuthenticatedModulesApiRoute
  '/modules/architecture': typeof AuthenticatedModulesArchitectureRoute
  '/modules/assistant': typeof AuthenticatedModulesAssistantRoute
  '/modules/database': typeof AuthenticatedModulesDatabaseRoute
  '/modules/documentation': typeof AuthenticatedModulesDocumentationRoute
  '/modules/knowledge': typeof AuthenticatedModulesKnowledgeRoute
  '/modules/quality': typeof AuthenticatedModulesQualityRoute
  '/modules/repository': typeof AuthenticatedModulesRepositoryRoute
  '/modules/requirements': typeof AuthenticatedModulesRequirementsRoute
  '/modules/risks': typeof AuthenticatedModulesRisksRoute
  '/modules/security': typeof AuthenticatedModulesSecurityRoute
  '/modules/team': typeof AuthenticatedModulesTeamRoute
  '/modules/tests': typeof AuthenticatedModulesTestsRoute
  '/modules/uiux': typeof AuthenticatedModulesUiuxRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/login/$role': typeof LoginRoleRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/modules/api': typeof AuthenticatedModulesApiRoute
  '/_authenticated/modules/architecture': typeof AuthenticatedModulesArchitectureRoute
  '/_authenticated/modules/assistant': typeof AuthenticatedModulesAssistantRoute
  '/_authenticated/modules/database': typeof AuthenticatedModulesDatabaseRoute
  '/_authenticated/modules/documentation': typeof AuthenticatedModulesDocumentationRoute
  '/_authenticated/modules/knowledge': typeof AuthenticatedModulesKnowledgeRoute
  '/_authenticated/modules/quality': typeof AuthenticatedModulesQualityRoute
  '/_authenticated/modules/repository': typeof AuthenticatedModulesRepositoryRoute
  '/_authenticated/modules/requirements': typeof AuthenticatedModulesRequirementsRoute
  '/_authenticated/modules/risks': typeof AuthenticatedModulesRisksRoute
  '/_authenticated/modules/security': typeof AuthenticatedModulesSecurityRoute
  '/_authenticated/modules/team': typeof AuthenticatedModulesTeamRoute
  '/_authenticated/modules/tests': typeof AuthenticatedModulesTestsRoute
  '/_authenticated/modules/uiux': typeof AuthenticatedModulesUiuxRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/login/$role'
    | '/login/'
    | '/modules/api'
    | '/modules/architecture'
    | '/modules/assistant'
    | '/modules/database'
    | '/modules/documentation'
    | '/modules/knowledge'
    | '/modules/quality'
    | '/modules/repository'
    | '/modules/requirements'
    | '/modules/risks'
    | '/modules/security'
    | '/modules/team'
    | '/modules/tests'
    | '/modules/uiux'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/login/$role'
    | '/login'
    | '/modules/api'
    | '/modules/architecture'
    | '/modules/assistant'
    | '/modules/database'
    | '/modules/documentation'
    | '/modules/knowledge'
    | '/modules/quality'
    | '/modules/repository'
    | '/modules/requirements'
    | '/modules/risks'
    | '/modules/security'
    | '/modules/team'
    | '/modules/tests'
    | '/modules/uiux'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/login/$role'
    | '/login/'
    | '/_authenticated/modules/api'
    | '/_authenticated/modules/architecture'
    | '/_authenticated/modules/assistant'
    | '/_authenticated/modules/database'
    | '/_authenticated/modules/documentation'
    | '/_authenticated/modules/knowledge'
    | '/_authenticated/modules/quality'
    | '/_authenticated/modules/repository'
    | '/_authenticated/modules/requirements'
    | '/_authenticated/modules/risks'
    | '/_authenticated/modules/security'
    | '/_authenticated/modules/team'
    | '/_authenticated/modules/tests'
    | '/_authenticated/modules/uiux'
    | '/_authenticated/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoleRoute: typeof LoginRoleRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$role': {
      id: '/login/$role'
      path: '/login/$role'
      fullPath: '/login/$role'
      preLoaderRoute: typeof LoginRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/uiux': {
      id: '/_authenticated/modules/uiux'
      path: '/modules/uiux'
      fullPath: '/modules/uiux'
      preLoaderRoute: typeof AuthenticatedModulesUiuxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/tests': {
      id: '/_authenticated/modules/tests'
      path: '/modules/tests'
      fullPath: '/modules/tests'
      preLoaderRoute: typeof AuthenticatedModulesTestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/team': {
      id: '/_authenticated/modules/team'
      path: '/modules/team'
      fullPath: '/modules/team'
      preLoaderRoute: typeof AuthenticatedModulesTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/security': {
      id: '/_authenticated/modules/security'
      path: '/modules/security'
      fullPath: '/modules/security'
      preLoaderRoute: typeof AuthenticatedModulesSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/risks': {
      id: '/_authenticated/modules/risks'
      path: '/modules/risks'
      fullPath: '/modules/risks'
      preLoaderRoute: typeof AuthenticatedModulesRisksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/requirements': {
      id: '/_authenticated/modules/requirements'
      path: '/modules/requirements'
      fullPath: '/modules/requirements'
      preLoaderRoute: typeof AuthenticatedModulesRequirementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/repository': {
      id: '/_authenticated/modules/repository'
      path: '/modules/repository'
      fullPath: '/modules/repository'
      preLoaderRoute: typeof AuthenticatedModulesRepositoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/quality': {
      id: '/_authenticated/modules/quality'
      path: '/modules/quality'
      fullPath: '/modules/quality'
      preLoaderRoute: typeof AuthenticatedModulesQualityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/knowledge': {
      id: '/_authenticated/modules/knowledge'
      path: '/modules/knowledge'
      fullPath: '/modules/knowledge'
      preLoaderRoute: typeof AuthenticatedModulesKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/documentation': {
      id: '/_authenticated/modules/documentation'
      path: '/modules/documentation'
      fullPath: '/modules/documentation'
      preLoaderRoute: typeof AuthenticatedModulesDocumentationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/database': {
      id: '/_authenticated/modules/database'
      path: '/modules/database'
      fullPath: '/modules/database'
      preLoaderRoute: typeof AuthenticatedModulesDatabaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/assistant': {
      id: '/_authenticated/modules/assistant'
      path: '/modules/assistant'
      fullPath: '/modules/assistant'
      preLoaderRoute: typeof AuthenticatedModulesAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/architecture': {
      id: '/_authenticated/modules/architecture'
      path: '/modules/architecture'
      fullPath: '/modules/architecture'
      preLoaderRoute: typeof AuthenticatedModulesArchitectureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/api': {
      id: '/_authenticated/modules/api'
      path: '/modules/api'
      fullPath: '/modules/api'
      preLoaderRoute: typeof AuthenticatedModulesApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedModulesApiRoute: typeof AuthenticatedModulesApiRoute
  AuthenticatedModulesArchitectureRoute: typeof AuthenticatedModulesArchitectureRoute
  AuthenticatedModulesAssistantRoute: typeof AuthenticatedModulesAssistantRoute
  AuthenticatedModulesDatabaseRoute: typeof AuthenticatedModulesDatabaseRoute
  AuthenticatedModulesDocumentationRoute: typeof AuthenticatedModulesDocumentationRoute
  AuthenticatedModulesKnowledgeRoute: typeof AuthenticatedModulesKnowledgeRoute
  AuthenticatedModulesQualityRoute: typeof AuthenticatedModulesQualityRoute
  AuthenticatedModulesRepositoryRoute: typeof AuthenticatedModulesRepositoryRoute
  AuthenticatedModulesRequirementsRoute: typeof AuthenticatedModulesRequirementsRoute
  AuthenticatedModulesRisksRoute: typeof AuthenticatedModulesRisksRoute
  AuthenticatedModulesSecurityRoute: typeof AuthenticatedModulesSecurityRoute
  AuthenticatedModulesTeamRoute: typeof AuthenticatedModulesTeamRoute
  AuthenticatedModulesTestsRoute: typeof AuthenticatedModulesTestsRoute
  AuthenticatedModulesUiuxRoute: typeof AuthenticatedModulesUiuxRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedModulesApiRoute: AuthenticatedModulesApiRoute,
  AuthenticatedModulesArchitectureRoute: AuthenticatedModulesArchitectureRoute,
  AuthenticatedModulesAssistantRoute: AuthenticatedModulesAssistantRoute,
  AuthenticatedModulesDatabaseRoute: AuthenticatedModulesDatabaseRoute,
  AuthenticatedModulesDocumentationRoute:
    AuthenticatedModulesDocumentationRoute,
  AuthenticatedModulesKnowledgeRoute: AuthenticatedModulesKnowledgeRoute,
  AuthenticatedModulesQualityRoute: AuthenticatedModulesQualityRoute,
  AuthenticatedModulesRepositoryRoute: AuthenticatedModulesRepositoryRoute,
  AuthenticatedModulesRequirementsRoute: AuthenticatedModulesRequirementsRoute,
  AuthenticatedModulesRisksRoute: AuthenticatedModulesRisksRoute,
  AuthenticatedModulesSecurityRoute: AuthenticatedModulesSecurityRoute,
  AuthenticatedModulesTeamRoute: AuthenticatedModulesTeamRoute,
  AuthenticatedModulesTestsRoute: AuthenticatedModulesTestsRoute,
  AuthenticatedModulesUiuxRoute: AuthenticatedModulesUiuxRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoleRoute: LoginRoleRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
